### ISSUE TITLE
Queries based on columns not working

### ISSUE THREAD

**Issue by talltyler** [wistityhq/waterline-graphql#10]
`query={users(id:"1"){username}}`
returns
`"Unknown argument \"id\" on field \"users\" of type \"Schema\".`

From my understanding this should return the first user. I've tried a few different ways of writing it but the issue seems to be that the column names have not been exposed as graphQL arguments.

**Comment by Aurelsicoko** [comment]
Sorry for the delay, I have not taken a look at this repository for a long time... Is this issue still relevant?

**Comment by talltyler** [comment]
I didn't pick up this issue and fix it, if this is what you are asking. I would suggest noting in the readme that your code isn't maintained or production ready or whatever.

**Comment by Aurelsicoko** [comment]
Many projects are using this package in production. Can you add the Waterline model in your first post? I can't imagine that the properties are not exposed in the GraphQL schema.

Are you using this package with Strapi, Sails or others?

Thanks!
